name: Build & Deploy SEC 1.05 Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"   # hourly at :15 (UTC)
  push:
    paths:
      - edgar_105_to_json.py
      - requirements.txt
      - .github/workflows/pages.yml
      - public/**

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Generate the latest JSON
      - name: Generate feed
        run: python edgar_105_to_json.py --out public/sec-105.json --days 180
        env:
          # REQUIRED: set this in repo Settings → Secrets and variables → Actions
          SEC_CONTACT_EMAIL: ${{ secrets.SEC_CONTACT_EMAIL }}

      # ---- Diff against last published to detect NEW items ----
      - name: Fetch previously published feed
        run: |
          curl -fsSL https://edencyber.github.io/sec-105-feed/sec-105.json -o old.json \
          || (echo '{"results":[]}' > old.json)

      - id: diff
        name: Find new entries
        run: |
          python - <<'PY'
          import os, json
          new = json.load(open('public/sec-105.json'))
          try:
            old = json.load(open('old.json'))
          except Exception:
            old = {"results": []}
          def rec_id(x):
            return x.get('document_href') or x.get('filing_href') or f"{x.get('cik')}-{x.get('filing_date')}"
          old_ids = {rec_id(x) for x in old.get('results', []) if rec_id(x)}
          fresh = [x for x in new.get('results', []) if rec_id(x) not in old_ids]
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            fh.write(f"has_new={'true' if fresh else 'false'}\n")
            if fresh:
              first = fresh[0]
              title = f"New SEC 1.05 filing: {first.get('company_name','')}"
              msg = f"{first.get('company_name','')} ({first.get('ticker','')}) on {first.get('filing_date','')}"
              url = first.get('filing_href','https://edencyber.com/')
              fh.write(f"title={title}\n")
              fh.write(f"msg={msg}\n")
              fh.write(f"url={url}\n")
          PY

      # ---- Option C: personal alerts (enable any you like by adding secrets) ----

      # Slack
      - name: Slack notify (optional)
        if: ${{ steps.diff.outputs.has_new == 'true' && secrets.SLACK_WEBHOOK_URL != '' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TITLE: ${{ steps.diff.outputs.title }}
          MSG: ${{ steps.diff.outputs.msg }}
          URL: ${{ steps.diff.outputs.url }}
        run: |
          echo "{\"text\": \"*${TITLE}*\n${MSG}\n<${URL}|View filing>\"}" > slack.json
          curl -sS -X POST -H 'Content-type: application/json' --data @slack.json "$SLACK_WEBHOOK_URL"

      # Microsoft Teams
      - name: Teams notify (optional)
        if: ${{ steps.diff.outputs.has_new == 'true' && secrets.TEAMS_WEBHOOK_URL != '' }}
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          TITLE: ${{ steps.diff.outputs.title }}
          MSG: ${{ steps.diff.outputs.msg }}
          URL: ${{ steps.diff.outputs.url }}
        run: |
          cat > teams.json <<JSON
          {
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "summary": "${TITLE}",
            "themeColor": "0078D7",
            "title": "${TITLE}",
            "text": "${MSG}",
            "potentialAction": [{
              "@type": "OpenUri",
              "name": "View filing",
              "targets": [{"os": "default", "uri": "${URL}"}]
            }]
          }
          JSON
          curl -sS -H "Content-Type: application/json" -d @teams.json "$TEAMS_WEBHOOK_URL"

      # Telegram
      - name: Telegram notify (optional)
        if: ${{ steps.diff.outputs.has_new == 'true' && secrets.TELEGRAM_BOT_TOKEN != '' && secrets.TELEGRAM_CHAT_ID != '' }}
        env:
          TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT: ${{ secrets.TELEGRAM_CHAT_ID }}
          TITLE: ${{ steps.diff.outputs.title }}
          MSG: ${{ steps.diff.outputs.msg }}
          URL: ${{ steps.diff.outputs.url }}
        run: |
          TEXT="*${TITLE}*\n${MSG}\n${URL}"
          curl -sS "https://api.telegram.org/bot${TOKEN}/sendMessage" \
            -d chat_id="${CHAT}" -d text="${TEXT}" -d parse_mode="Markdown" \
            -d disable_web_page_preview=true

      # Pushover
      - name: Pushover notify (optional)
        if: ${{ steps.diff.outputs.has_new == 'true' && secrets.PUSHOVER_APP_TOKEN != '' && secrets.PUSHOVER_USER_KEY != '' }}
        env:
          APP: ${{ secrets.PUSHOVER_APP_TOKEN }}
          USER: ${{ secrets.PUSHOVER_USER_KEY }}
          TITLE: ${{ steps.diff.outputs.title }}
          MSG: ${{ steps.diff.outputs.msg }}
          URL: ${{ steps.diff.outputs.url }}
        run: |
          curl -sS -X POST https://api.pushover.net/1/messages.json \
            -d token="$APP" -d user="$USER" \
            -d title="$TITLE" -d message="$MSG" -d url="$URL" -d ttl=3600

      # ---- Publish to GitHub Pages ----
      - uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
